<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="spirit">

	<!-- Define parameters -->
	<!-- bodyLength + hipdx should be equal to front to back hip distance -->
	<!-- dy +  dPodAxisToEdge + upperLegWidth should be equal to the center to toe distance along y axis-->
	<xacro:property name="pi" value="3.14159265359"/>
	<xacro:property name="bodyLength" value="0.335"/>
	<xacro:property name="bodyWidth" value="0.24"/>
	<xacro:property name="bodyHeight" value="0.104"/>
	<xacro:property name="bodyMass" value="5.75"/>
	<xacro:property name="podMass" value="0.575"/>
	<xacro:property name="upperLegMass" value="0.775"/>
	<xacro:property name="upperLegIxx" value="0.00005"/> <!-- guess -->
	<xacro:property name="upperLegIyy" value="0.001"/> <!-- guess -->
	<xacro:property name="upperLegIzz" value="0.001"/> <!-- guess -->
	<xacro:property name="lowerLegMass" value="0.075"/>
	<xacro:property name="lowerLegIxx" value="0.000005"/> <!-- guess -->
	<xacro:property name="lowerLegIyy" value="0.0001"/> <!-- guess -->
	<xacro:property name="lowerLegIzz" value="0.0001"/> <!-- guess -->
	<xacro:property name="toeMass" value="0.015"/>
	<xacro:property name="upperLegLength" value="0.206"/>
	<xacro:property name="upperLegWidth" value="0.022"/>
	<xacro:property name="upperLegHeight" value="0.055"/>
	<xacro:property name="lowerLegLength" value="0.206"/>
	<xacro:property name="lowerLegRadius" value="0.013"/> <!--visual only-->
	<xacro:property name="podLength" value="0.08"/>
	<xacro:property name="podRadius" value="0.055"/>
	<xacro:property name="dPodAxisToEdge" value="0.028"/> <!--center of pod cylinder to the ab axis-->
	<xacro:property name="abOffs" value="0.10098"/>
	<xacro:property name="dx" value="0.2263"/>
	<xacro:property name="dy" value="0.07"/>
	<xacro:property name="toeRadius" value="0.02"/>
	<xacro:property name="toeOffset" value="0.0"/>
	<xacro:property name="toeStiffness" value="30000.0"/>
	<xacro:property name="toeDamping" value="1000.0"/>
	<xacro:property name="toeSpinningFriction" value="0.3"/>
    <xacro:property name="toeFriction" value="100.0"/> <!-- originally 100 -->
	<xacro:property name="toeLateralFriction" value="50.0"/> <!-- originally 50 -->
	<xacro:property name="abKinLimit" value="0.707"/>
	<xacro:property name="abSpeedLimit" value="30"/>
	<xacro:property name="abEffortLimit" value="40"/>
	<xacro:property name="jointSpeedLimit" value="30"/>
	<xacro:property name="jointEffortLimit" value="40"/>

	<!-- Define materials -->
	<material name="darkgray">
		<color rgba="0.1 0.1 0.1 1.0"/>
	</material>
	<material name="silver">
		<color rgba="0.3 0.3 0.3 1.0"/>
	</material>
	<material name="red">
		<color rgba="0.8 0.0 0.2 1.0"/>
	</material>

	<!-- Body -->
	<link name="body">
		<!-- <visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
			</geometry>
			<material name="darkgray"/>
		</visual> -->

		<visual>
			<origin rpy="0 0 0" xyz="0.03 0 0"/>
			<geometry>
				<mesh filename="file://$(arg mesh_dir)/Spirit40/Spirit40_Body_Mesh_transformed.stl"
							scale="1 1 1"/>
			</geometry>
			<material name="darkgray"/>
		</visual>

		<inertial>
			<mass value="${bodyMass}"/>
			<!-- Uniform box -->
			<!-- <inertia ixx="1/12*${bodyMass}*(${bodyWidth}*${bodyWidth} + ${bodyHeight}*${bodyHeight})"  ixy="0"  ixz="0" iyy="1/12*${bodyMass}*(${bodyLength}*${bodyLength} + ${bodyHeight}*${bodyHeight})" iyz="0" izz="1/12*${bodyMass}*(${bodyLength}*${bodyLength} + ${bodyWidth}*${bodyWidth})"/> -->
			<inertia ixx="0.05"  ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			<!-- Training Wheels: No Rotation -->
			<!-- <inertia ixx="1000"  ixy="0"  ixz="0" iyy="100000" iyz="0" izz="1000" /> -->
			<!-- Training Wheels: Sagittal Rotation Only -->
			<!-- <inertia ixx="1000"  ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="1000" /> -->
		</inertial>

		<!-- Just copy geometry for collision -->
		<collision>
		<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
			</geometry>
		</collision>
	</link>
	<!-- <gazebo reference="body">
        <material>Gazebo/Gray</material>
    </gazebo> -->

	<link name="base_link"/>
	<joint name="base_link_to_body" type="fixed">
		<parent link="base_link"/>
		<child link="body"/>
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
	</joint>

	<!-- <link name="base_link"/>
			 <xacro:insert_block name="bodyInertial"/>
	</link> -->
	<!-- <joint name="body_joint" type="fixed">
			<parent link="body"/>
			<child link="base_link"/>
			<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
			<axis xyz="1 0 0"/>
	</joint> -->

	<!-- this way planner can run unchanged-->
	<link name="t265_pose_frame"/>
	<joint name="body_to_t265" type="fixed">
		<parent link="body"/>
		<child link="t265_pose_frame"/>
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
	</joint>

	<gazebo reference="body">
		<gravity>true</gravity>
		<sensor name="imu_sensor" type="imu"> <!-- This might be completely unneccesary -->
			<always_on>true</always_on> <!-- Set this in sensor's sdf -->
			<visualize>true</visualize>
			<topic>__default_topic_</topic>
			<plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
				<!-- <topicName>imu</topicName> -->
				<bodyName>body</bodyName>
				<ros>
				<!-- Will publish to /imu-->
						<namespace>/</namespace>
					 <argument>imu:=data</argument> <!-- I think this is ok to comment out, so it publishes to /imu???-->
				</ros>
				<!-- <updateRateHZ>500.0</updateRateHZ> TODO SET THIS IN THE SENSOR'S SDF! -->
				<!-- <gaussianNoise>0.0</gaussianNoise> -->
				<!-- <xyzOffset>0 0 0</xyzOffset>
				<rpyOffset>0 0 0</rpyOffset> -->
				<frame_name>body</frame_name>
				<initialOrientationAsReference>true</initialOrientationAsReference>
			</plugin>
			<pose>0 0 0 0 0 0</pose>
		</sensor>
	</gazebo>

	<!-- Define our leg macro -->
	<xacro:macro name="leg" params="suffix left front hipJointName kneeJointName abductionJointName hipJointLowerLimit hipJointUpperLimit color">

		<!-- Hip motor -->
		<link name="hip${suffix}">
			<visual>
				<!-- <origin rpy="${pi/2} 0 0" xyz="${front * 0} ${left * (dPodAxisToEdge)} 0"/> -->
				<!-- <geometry>
					<cylinder length="${podLength}" radius="${podRadius}"/>
				</geometry> -->
				<!-- <material name="${color}"/>
			</visual>
			<visual> -->

				<geometry>
					<mesh filename="file://$(arg mesh_dir)/Spirit40/Spirit40_Hip_Module_transformed.stl"
						  scale="1 1 1"/>
				</geometry>
				<xacro:if value="${front == 1 and left == 1}">
					<origin rpy="0 0 0" xyz="0 0.0 0"/>
				</xacro:if>

				<xacro:if value="${front == -1 and left == 1}">
					<origin rpy="0 ${pi} 0" xyz="0.0 0.0 0"/>
				</xacro:if>

				<xacro:if value="${front == 1 and left == -1}">
					<origin rpy="${pi} 0 0" xyz="0.0 0 0.0"/>
				</xacro:if>

				<xacro:if value="${front == -1 and left == -1}">
					<origin rpy="${pi} ${pi} 0" xyz="0.0 0.0 0.0"/>
				</xacro:if>

				<!-- <geometry>
					<mesh filename="file://$(arg mesh_dir)/Spirit40/Spirit40_Hip_Module_transformed.stl"
						  scale="1 1 1"/>
				</geometry> -->

				<material name="darkgray"/>
			</visual>

			<collision>
				<origin rpy="${pi/2} 0 0" xyz="0 ${left * (dPodAxisToEdge)} 0"/>
				<geometry>
					<cylinder length="${podLength}" radius="${podRadius}"/>
				</geometry>
			</collision>

			<inertial>
				<mass value="${podMass}"/>
				<!-- <inertia ixx="1/12*${podMass}*${podLength}*${podLength} + 1/4*${podMass}*${podRadius}*${podRadius}"  ixy="0"  ixz="0" iyy="1/12*${podMass}*${podLength}*${podLength} + 1/4*${podMass}*${podRadius}*${podRadius}" iyz="0" izz="1/2*${podMass}*${podRadius}*$
				{podRadius}" /> -->
				<inertia ixx="0.00066963541"  ixy="0"  ixz="0" iyy="0.00066963541" iyz="0" izz="0.0008696875" />
			</inertial>
		</link>
		<gazebo reference="hip${suffix}">
            <material>Gazebo/Gray</material>
        </gazebo>

		<!-- Abduction joint. Joint names are: 8 9 10 11 -->
		<joint name="${abductionJointName}" type="revolute">
			<parent link="body"/>
			<child link="hip${suffix}"/>
			<axis xyz="1 0 0"/>
			<origin xyz="${front * dx} ${left * dy} 0"/>
			<limit effort="${abEffortLimit}" velocity="${abSpeedLimit}" lower="${-abKinLimit}" upper="${abKinLimit}"/>
			<dynamics damping="0.0" friction="0.0"/>
			<!-- <dynamics damping="0.05" friction="0.160"/> -->

		</joint>

		<!-- Transmission elements required for Gazebo -->
        <transmission name="transmission_${abductionJointName}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${abductionJointName}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor_${abductionJointName}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

		<!-- Upper leg -->
		<link name="upper${suffix}">
			<visual>
				<!-- <origin rpy="0 0 0" xyz="-${upperLegLength/2} ${-left*upperLegWidth} 0"/> -->
				<!-- <geometry>
					<box size="${upperLegLength} ${upperLegWidth} ${upperLegHeight}"/>
				</geometry> -->
				<!-- <material name="silver"/>
			</visual>
			<visual> -->
				<xacro:if value="${left == 1}">
					<origin rpy="0 0  0" xyz="0 -0.02 0"/>
				</xacro:if>

				<xacro:if value="${left == -1}">
					<origin rpy="${pi} 0  0" xyz="0 0.02 0"/>
				</xacro:if>
				<geometry>
					<mesh filename="file://$(arg mesh_dir)/Spirit40/Spirit40_Upper_leg_transformed.stl"
						  scale="1 1 1"/>
				</geometry>

				<material name="darkgray"/>
			</visual>

			<collision>
				<origin rpy="0 0 0" xyz="-${upperLegLength/2} ${-left*upperLegWidth} 0"/>
				<geometry>
					<box size="${upperLegLength} ${upperLegWidth} ${upperLegHeight}"/>
				</geometry>
			</collision>

			<inertial>
				<mass value="${upperLegMass}"/>
				<inertia ixx="${upperLegIxx}"  ixy="0" ixz="0" iyy="${upperLegIyy}" iyz="0" izz="${upperLegIzz}"/>
			</inertial>
		</link>
		<gazebo reference="upper${suffix}">
            <material>Gazebo/Gray</material>
        </gazebo>

		<!-- Hip joint. (Motor to upper leg). Joint names are: 0 2 4 6 -->
		<joint name="${hipJointName}" type="revolute">
			<parent link="hip${suffix}"/>
			<child link="upper${suffix}"/>
			<axis xyz="0 -1 0"/>
			<origin xyz="${front * 0} ${left * abOffs} 0"/> <!--  rpy="0 -0.3 0" -->
			<limit effort="${jointEffortLimit}" velocity="${jointSpeedLimit}" lower="${hipJointLowerLimit}" upper="${hipJointUpperLimit}"/>
			<!--dynamics damping="0.05" friction="0.160"/-->
			<dynamics damping="0.0" friction="0.0"/>
			<!-- Originally, these were set to 0.0 and 0.0.  I'm trying to adjust them to see if I can get the robot to not jitter as much. -->
		</joint>

		<!-- Transmission elements required for Gazebo -->
        <transmission name="transmission_${hipJointName}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${hipJointName}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor_${hipJointName}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

		<!-- Lower leg -->
		<link name="lower${suffix}">
			<visual>
				<!-- <origin rpy="0 ${pi/2} 0" xyz="${lowerLegLength/2} 0 0"/> -->
				<!-- <geometry>
					<cylinder length="${lowerLegLength}" radius="${lowerLegRadius}"/>
				</geometry> -->
				<!-- <material name="darkgray"/>
			</visual>
			<visual> -->
				<xacro:if value="${left == 1}">
					<origin rpy="0 0  0" xyz="0 0 0"/>
				</xacro:if>

				<xacro:if value="${left == -1}">
					<origin rpy="${pi} 0  0" xyz="0 0 0"/>
				</xacro:if>
				<geometry>
					<mesh filename="file://$(arg mesh_dir)/Spirit40/Spirit40_Lower_Leg_transformed.stl"
						  scale="1 1 1"/>
				</geometry>

				<material name="darkgray"/>
			</visual>

			<collision>
				<origin rpy="0 ${pi/2} 0" xyz="${lowerLegLength/2} 0 0"/>
				<geometry>
					<cylinder length="${lowerLegLength}" radius="${lowerLegRadius}"/>
				</geometry>
			</collision>

			<inertial>
				<mass value="${lowerLegMass}"/>
				<inertia ixx="${lowerLegIxx}"  ixy="0" ixz="0" iyy="${lowerLegIyy}" iyz="0" izz="${lowerLegIzz}"/>
			</inertial>
		</link>

		<gazebo reference="lower${suffix}">
            <material>Gazebo/Black</material>
        </gazebo>

		<!-- Knee joint. Joint names are: 1 3 5 7 -->
		<joint name="${kneeJointName}" type="revolute">
			<parent link="upper${suffix}"/>
			<child link="lower${suffix}"/>
			<axis xyz="0 1 0"/>
			<origin xyz="-${upperLegLength} 0 0"/> <!--rpy="0 0.5 0"-->
			<limit effort="${jointEffortLimit}" velocity="${jointSpeedLimit}" lower="-${pi}" upper="${pi}"/>

			<!-- <dynamics damping="0.1" friction="1.05"/> -->
			<dynamics damping="0.0" friction="0.0"/>
			<!-- Originally, these were set to 0.0 and 0.0.  I'm trying to adjust them to see if I can get the robot to not spazz out as much. -->
		</joint>

		<!-- Transmission elements required for Gazebo -->
        <transmission name="transmission_${kneeJointName}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${kneeJointName}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor_${kneeJointName}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

		<!-- Toe -->
		<link name="toe${suffix}">
			<contact>
				<friction_anchor/>
				<stiffness value="${toeStiffness}"/>
				<damping value="${toeDamping}"/>
				<spinning_friction value="${toeSpinningFriction}"/>
				<lateral_friction value="${toeLateralFriction}"/>
			</contact>
			<visual>
				<origin rpy="0 0 0" xyz="0 0 0"/>
				<geometry>
<!--					<sphere radius="${toeRadius}"/>-->
					<sphere radius="0.001"/>
				</geometry>
				<material name="darkgray"/>
			</visual>

			<collision>
				<origin rpy="0 0 0" xyz="0 0 0"/>
				<geometry>
					<sphere radius="${toeRadius}"/>
				</geometry>
				<surface>
					<friction>
						<ode>
							<mu>100000</mu>
							<mu2>100000</mu2>
						</ode>
					</friction>
					<contact>
						<ode>
							<kp>${toeStiffness}</kp>
							<kd>${toeDamping}</kd>
						</ode>
					</contact>
				</surface>
			</collision>

			<inertial>
				<mass value="${toeMass}"/>
				<inertia ixx="0.000025"  ixy="0"  ixz="0" iyy="0.000025" iyz="0" izz="0.000025" />
				<!-- <inertia ixx="2/5*${toeMass}*${toeRadius}*${toeRadius}"  ixy="0"  ixz="0" iyy="2/5*${toeMass}*${toeRadius}*${toeRadius}" iyz="0" izz="2/5*${toeMass}*${toeRadius}*${toeRadius}" /> -->
			</inertial>
		</link>

		<gazebo reference="toe${suffix}">
<!--			<sensor name="toe${suffix}_contact" type="contact">-->
<!--				<always_on>true</always_on>-->
<!--				<update_rate>400.0</update_rate>-->
<!--				<contact>-->
<!--					<collision>lower${suffix}_fixed_joint_lump__toe${suffix}_collision_1</collision>-->
<!--				</contact>-->
<!--				<plugin name="gripper_bumper" filename="libgazebo_ros_bumper.so">-->
<!--					<bumperTopicName>toe${suffix}_collision</bumperTopicName>-->
<!--					<frameName>toe${suffix}</frameName>-->
<!--				</plugin>-->
<!--			</sensor>-->
			<material>Gazebo/DarkGray</material>
			<collision>
				<surface>
					<bounce>
						<restitution_coefficient>0</restitution_coefficient>
						<threshold>1e+06</threshold>
					</bounce>
					<friction>
						<torsional>
							<coefficient>${toeSpinningFriction}</coefficient>
						</torsional>
						<ode>
							<mu>${toeFriction}</mu>
							<mu2>${toeLateralFriction}</mu2>
						</ode>
						<bullet>
							<rolling_friction>${toeSpinningFriction}</rolling_friction>
							<friction2>${toeLateralFriction}</friction2>
						</bullet>
					</friction>
					<contact>
						<bullet>
							<kp>${toeStiffness}</kp>
							<kd>${toeDamping}</kd>
						</bullet>
						<ode>
							<kp>${toeStiffness}</kp>
							<kd>${toeDamping}</kd>
						</ode>
					</contact>
				</surface>
			</collision>
		</gazebo>

		<joint name="jtoe${suffix}" type="fixed">
			<parent link="lower${suffix}"/>
			<child link="toe${suffix}"/>
			<origin xyz="${lowerLegLength} 0 -${toeOffset}"/>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>

	</xacro:macro>

	<!-- Our four legs -->
	<xacro:leg suffix="0" hipJointName="0" kneeJointName="1" abductionJointName="8" front="1" left="1" hipJointLowerLimit="${-2*pi}" hipJointUpperLimit="${2*pi}" color="darkgray"/>
 	<xacro:leg suffix="1" hipJointName="2" kneeJointName="3" abductionJointName="9" front="-1" left="1" hipJointLowerLimit="${-2*pi}" hipJointUpperLimit="${2*pi}" color="darkgray"/>
 	<xacro:leg suffix="2" hipJointName="4" kneeJointName="5" abductionJointName="10" front="1" left="-1" hipJointLowerLimit="${-2*pi}" hipJointUpperLimit="${2*pi}" color="red"/>
 	<xacro:leg suffix="3" hipJointName="6" kneeJointName="7" abductionJointName="11" front="-1" left="-1" hipJointLowerLimit="${-2*pi}" hipJointUpperLimit="${2*pi}" color="darkgray"/>

 	<!-- Add ros_control plugin -->
	<xacro:if value="$(arg use_gazebo)">
            <ros2_control name="GazeboSystem" type="system">
                <hardware>
                    <plugin>gazebo_ros2_control/GazeboSystem</plugin>
                </hardware>
                <joint name="0">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="1">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="2">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="3">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="4">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="5">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="6">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="7">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="8">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="9">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="10">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
                <joint name="11">
                    <command_interface name="effort">
                        <param name="min">-1000</param>
                        <param name="max">1000</param>
                    </command_interface>
                    <state_interface name="position"/>
                    <state_interface name="velocity"/>
                    <state_interface name="effort"/>
                </joint>
            </ros2_control>
           <gazebo reference="body">
               <material>Gazebo/DarkGray</material>
           </gazebo>
            <!-- Add ros_control plugin -->
            <gazebo>
                <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
                    <robot_sim_type>gazebo_ros2_control/GazeboSystem</robot_sim_type>
                    <robot_param>robot_description</robot_param>
                    <robot_param_node>robot_state_publisher</robot_param_node>
                    <parameters>$(find ros2_ghost_gazebo)/controllers/spirit40.yaml</parameters>
<!--                    <control_period>0.001</control_period>-->
                    <!--                    <e_stop_topic>/cart_pole/estop</e_stop_topic>-->
                </plugin>
                <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>500.0</updateRate>
                    <body_name>base_link</body_name>
                    <topic_name>odom</topic_name>
                    <gaussianNoise>0.0</gaussianNoise>
                    <frame_name>world</frame_name>
                    <xyzOffsets>0 0 0</xyzOffsets>
                    <rpyOffsets>0 0 0</rpyOffsets>
                </plugin>
            </gazebo>
        </xacro:if>
</robot>
